#!/bin/bash

export VAULT_UNIT_IP=$(juju run --unit vault/leader "network-get access --ingress-address=true"); export VAULT_ADDR="http://$VAULT_UNIT_IP:8200"

root_token=$(jq -r '.root_token' k)
export VAULT_TOKEN=$root_token
vault token create --ttl=10m --format json > t
