description: A highly-available, production-grade Kubernetes cluster.
debug:                      &debug                     True
verbose:                    &verbose                   True

machines:
  '0':
    constraints: arch=amd64 tags=compute
    series: bionic
  '1':
    constraints: arch=amd64 tags=compute
    series: bionic
  '2':
    constraints: arch=amd64 tags=compute
    series: bionic
  '3':
    constraints: arch=amd64 tags=compute
    series: bionic
  '4':
    constraints: arch=amd64 tags=compute
    series: bionic
  '5':
    constraints: arch=amd64 tags=node
    series: bionic
  '6':
    constraints: arch=amd64 tags=node
    series: bionic
  '7':
    constraints: arch=amd64 tags=node
    series: bionic
  '8':
    constraints: arch=amd64 tags=node
    series: bionic
  '9':
    constraints: arch=amd64 tags=node
    series: bionic
series: bionic
services:
  easyrsa:
    charm: cs:~containers/easyrsa-192
    num_units: 1
    to:
    - lxd:0
  etcd:
    charm: cs:~containers/etcd-332
    num_units: 3
    options:
      channel: 3.2/stable
    to:
    - 6
    - 7
    - 8
  flannel:
    charm: cs:~containers/flannel
  kubeapi-load-balancer:
    charm: cs:~containers/kubeapi-load-balancer-520
    expose: true
    num_units: 1
    to:
    - 9
  kubernetes-master:
    charm: cs:~containers/kubernetes-master-539
    num_units: 2
    options:
      channel: 1.12/stable
    to:
    - 4
    - 5
  kubernetes-worker:
    charm: cs:~containers/kubernetes-worker-395
    expose: true
    num_units: 3
    options:
      channel: 1.12/stable
    to:
    - 1
    - 2
    - 3
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
